version: "3.9"

services:
  postgres:
    image: postgresdata
    environment:
      POSTGRES_PASSWORD: postgres
  node:
    image: ponyeventdata
    build: .
    ports:
      - "9000:9000"
    env_file:
      - .env
    deploy:
      replicas: 1
    volumes:
      - dockervolume:/app
volumes:
  dockervolume: